### ISSUE TITLE
Mapping Postcodes to Constituencies for Facebook

### ISSUE THREAD

**Issue by L-A-Ryan** [PeoplesMomentum/projects#43]
Creating a way to easily target different constituencies using Facebook's advertising tool - likely to be a list of inclusion and exclusion criteria based on postcodes.

**Comment by dfl1955** [comment]
There is a postcode constituency map at https://www.doogal.co.uk/ElectoralConstituencies.php

**Comment by dfl1955** [comment]
The full database can be bought from the Post Code address file owners. Not sure of its costs.

http://www.postcodeaddressfile.co.uk/products/parliamentary_constituences/postcode_parliamentary_constituency.htm

**Comment by ElaineBeck** [comment]
Hi there, I'm happy to help with this. Is it just a spreadsheet required or another document?

**Comment by patnsmith** [comment]
The PAF is incredibly expensive for anything other than a single user license (which is still several hundred pounds). 

The Office for National Statistics produces a list of postcodes, latitudes, longitudes, constituencies and wards. I've linked to the data below. The parliamentary constituency codes need to be linked with the names, but other than that both files are a free, open data source from the government.

In the postcode file:
pcd is the postcode
pcon is the constituency code
lat is the latitude
lng is the longidute

In the parliament codes file:
PCON16CD is the code
PCON16NM is the name of the constituency.

The other issue is that each constituency has 2-3000 postcodes in it. 

I believe the Labour Party's "promote" tool gets around this by figuring out the minimum number of postcodes (plus radius) that cover a constituency. With the lat long data this should be trivial to calculate. 

Latest ONS data: http://parlvid.mysociety.org/os/ONSPD_MAY_2017.zip
Constituency and ward codes: http://geoportal.statistics.gov.uk/datasets/f52c48ea5cf2494b824d35f4be88f2ec_0
Resources: http://parlvid.mysociety.org/os/

**Comment by ElaineBeck** [comment]
What I have used for determining Postcodes is the ward/constituencies website. It tells you which posts are for which constituency. Again although time consuming I am willing to work on this. Put it a spreadsheet and then convert to a cvs. Just need the go ahead really.

**Comment by dan-fahey** [comment]
No spreadsheets

**Comment by ElaineBeck** [comment]
Then Dan how would the data be collected? If there is something else to complete I am happy to do that.

**Comment by alice-sowerby** [comment]
@dan-fahey I appreciate spreadsheets are often not appropriate, can you help us out with your thoughts on why not in this scenario and what else would be a better solution? Elaine is new, let's give her something to work with :)

**Comment by dfl1955** [comment]
I have a python program which reads two postcode lists, one of them designed to be a constituency list and report how many of the 1st list exist within the 2nd. It was written to allow an affiliated body to determine its affiliation entitlement. I used the doogal .csv files as my source. I plan to supplement this with a program that creates a list of those elements from the 1st file within the second file so that Union branches can identify their members within a CLP. 

Thanks to @dan-fahey for pointing at the government free resources.

.csv files are not spreadsheets, they are flat text files.

**Comment by dfl1955** [comment]
@L-A-Ryan might also help by documenting her requirements. Assume we can go from PC -> Ward -> Constituency and back

**Comment by ElaineBeck** [comment]
It seems my help is not required. Sounds brilliant, and I wish you loads of luck.

**Comment by alice-sowerby** [comment]
Thanks for offering your time and effort, Elaine, I'm sure there will be some projects where you will be able to help out.

**Comment by dfl1955** [comment]
@ElaineBeck I have uploaded my code to https://github.com/dfl1955/polpc. I might well appreciate your help. I need to understand the schema of the ONS data to translate it into something I can use. At the moment my code does not deal with wards so that's an additional piece of design.

Using a spreadsheet to create artefacts, i.e. .csv files is OK in my book. I am unclear as to when I plan to continue my work and research the ONS schema because my next task is to write a people in constituency report. 

May I ask for your help when this is done.

**Comment by dan-fahey** [comment]
I updated the script I wrote at the hackathon with this one using the data recommended by @patnsmith:
https://github.com/dan-fahey/party/blob/master/R/postcodes_ons.R

CSV here: https://raw.githubusercontent.com/dan-fahey/party/master/data/constituency_postcode_sectors.csv

Each constituency (650 nr total) has a corresponding list of postcode sectors.
